[package]
name = "xbytes"
version = "0.1.1"
authors = ["Miraculous Owonubi <mira@growthmate.xyz>"]
edition = "2024"
rust-version = "1.85"
description = "Convert between raw byte sizes and human readable sizes"
documentation = "https://docs.rs/xbytes"
readme = "README.md"
repository = "https://github.com/miraclx/xbytes-rs"
license = "MIT OR Apache-2.0"
keywords = ["bytes", "human-readable", "size", "parsing", "formatting"]
categories = ["value-formatting", "parsing"]

[features]
default = ["u128", "lossless", "no-panic"]
bits = []
u128 = []
lossless = ["fraction"]
no-panic = ["lossless"]
case-insensitive = []

[dependencies]
bitflags = "2.13"
fraction = { version = "0.17", optional = true }
thiserror = "2.0"
