[package]
name = "xbytes-rs"
version = "0.1.0"
authors = ["Miraclx <omiraculous@gmail.com>"]
edition = "2018"
description = "convert byte sizes to human readable sizes"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["u128"]
u128 = []
case-insensitive = []
